highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: 
title: Mehadi Hassan's Resume
name: Mehadi Hassan
email: mehadi.hassan<br>@g.bracu.ac.bd
email_full: mailto:mehadi.hassan@g.bracu.ac.bd
website: mehadihn.github.io
website_full: https://mehadihn.github.io
github: mehadihn
twitter: mehadihn
#tel: +44 0000 000000
#tel_full: tel:+440000000000
#google_maps: 'https://www.google.com/maps/place/Dhaka/@23.7839306,90.3287404,11.5z/data=!4m5!3m4!1s0x3755b8b087026b81:0x8fa563bbdd5904c2!8m2!3d23.810332!4d90.4125181'
address:
  #street: 44 Perth Street
  #postcode: EH3 5BL
  city: Dhaka
  country: Bangladesh
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
